---
- name: Configure CI server
  hosts: jenkins
  become: True
  vars:
    jenkins_http_port: 8181
    jenkins_hostname: 0.0.0.0
    #TODO - set nxt 2 
    jenkins_admin_username: admin
    jenkins_admin_password: admin
  pre_tasks:
    - include: java-8.yml
  roles:
    - shrikeh.curl
    - geerlingguy.java
    - geerlingguy.jenkins

