version: '3'
services:
  jenkins:
    env_file: jenkins.env
    build: 
      context: .
      dockerfile: Dockerfile_master
      args:
        jenkins_port: ${JENKINS_PORT}
        jenkins_host_port: ${JENKINS_HOST_PORT}
        jenkins_user: ${JENKINS_USER}
        jenkins_pass: ${JENKINS_PASS}
    image: zerogvt/jenkins:v1
    ports:
      - "${JENKINS_HOST_PORT}:${JENKINS_PORT}"

  slave_1:
    build: 
      context: .
      dockerfile: Dockerfile_node
    image: zerogvt/jenkins_slave:v1
    tty: true
    ports:
      - "2222:22"

  slave_2:
    build: 
      context: .
      dockerfile: Dockerfile_node
    image: zerogvt/jenkins_slave:v1
    tty: true
    ports:
      - "2223:22"
