version: '3'
services:
  jenkins:
    env_file: jenkins.env
    build: 
      context: .
      dockerfile: Dockerfile_master
      args:
        jenkins_port: 8180
        jenkins_host_port: 8182
        jenkins_user: vas
        jenkins_pass: vas
    image: zerogvt/jenkins:v1
    ports:
      - "8180:8182"

