version: '3'

networks:
  bridge:

volumes:
  shared-data:

services:
  jenkins:
    networks:
      - bridge
    env_file: jenkins.env
    build: 
      context: .
      dockerfile: Dockerfile_master
      # args injected via ENV_SUBTITUTION
      args:
        jenkins_port: ${JENKINS_PORT}
        jenkins_host_port: ${JENKINS_HOST_PORT}
        jenkins_user: ${JENKINS_USER}
        jenkins_pass: ${JENKINS_PASS}
        slave_1_name: ${SLAVE_1_NAME}
        slave_2_name: ${SLAVE_2_NAME}
    image: zerogvt/jenkins:v1
    ports:
      - "${JENKINS_HOST_PORT}:${JENKINS_PORT}"
    volumes:
      - shared-data:/var/cache/jenkins/war/WEB-INF/lib

# slaves templates hereon

